name: release

on:
  release:
    types: [ prereleased ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y libmbedtls-dev
       sudo apt-get install -y libmongoc-1.0-0 libmongoc-dev
       cd /usr/include
       sudo ln -s libmongoc-1.0/ mongoc
       sudo ln -s libbson-1.0/ bson       
    - name: Test make
      run: make
    - name: Test make re
      run: make re
    - name: Test make clean
      run: make clean
    - name: Test make fclean
      run: make fclean
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in on Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set version tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          hdeoliv/enki:${{ env.RELEASE_VERSION }}
          hdeoliv/enki:latest
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "enki-api"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: true
        
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create the release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: Automatic release triggered by CI.
